name = "gokhan-memex"
compatibility_date = "2024-01-15"

# Output directory for Pages
pages_build_output_dir = "build"

[env.production]
name = "gokhan-memex"

[env.production.vars]
NODE_ENV = "production"

[env.preview]
name = "gokhan-memex-preview"

[env.preview.vars]
NODE_ENV = "preview"
